### ISSUE TITLE
Nest camera (stream) doesn't work

### ISSUE THREAD

**Issue by zyphlar** [YunoHost-Apps/homeassistant_ynh#129]
### Describe the bug

HomeAssistant adds my Nest cam, but claims the Stream integration isn't set up. I can't find any info on setting it up other than old issues that imply that my configuration is weird. (My configuration is brand new, I just installed this package.)

### Context

Home Assistant 2022.8.6

YunoHost 4.4.2.9

### Logs

This in the GUI log. Installing ffmpeg via apt seems to have no improvement.

```
Error handling request
2:21:38 PM – (ERROR) components/stream/__init__.py
Error starting FFmpeg.
2:20:40 PM – (WARNING) /var/www/homeassistant/lib/python3.9/site-packages/haffmpeg/tools.py
FFmpeg fails [Errno 2] No such file or directory: 'ffmpeg'
2:20:40 PM – (ERROR) /var/www/homeassistant/lib/python3.9/site-packages/haffmpeg/core.py
```

This in the Yunohost logs, even after installing ffmpeg:

```
2022-08-19 21:21:38 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/var/www/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 738, in get
    return await self.handle(request, camera)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 778, in handle
    stream = await camera.handle_async_mjpeg_stream(request)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 605, in handle_async_mjpeg_stream
    return await self.handle_async_still_stream(request, self.frame_interval)
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 593, in handle_async_still_stream
    return await async_get_still_stream(
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 267, in async_get_still_stream
    img_bytes = await image_cb()
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/nest/camera_sdm.py", line 215, in async_camera_image
    stream = await self.async_create_stream()
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/camera/__init__.py", line 541, in async_create_stream
    self.stream = create_stream(
  File "/var/www/homeassistant/lib/python3.9/site-packages/homeassistant/components/stream/__init__.py", line 140, in create_stream
    raise HomeAssistantError("Stream integration is not set up.")
homeassistant.exceptions.HomeAssistantError: Stream integration is not set up.
```

**Comment by tituspijean** [comment]
Try `sudo apt install ffmpeg` and restart the Home Assistant service.

**Comment by ewilly** [comment]
FYI Home Assistant 2022.8.6 is not supported due to missing python dependencies, see #128 

Regarding the error message "homeassistant.exceptions.HomeAssistantError: Stream integration is not set up.", did you implement correctly the Nest integration ? 
[https://www.home-assistant.io/integrations/nest/#troubleshooting](https://www.home-assistant.io/integrations/nest/#troubleshooting) could be interesting.

**Comment by zyphlar** [comment]
I did everything I could, and like I said installing ffmpeg seemed to have no effect. It may be I needed to more aggressively restart the service but I'm not used to restarting things on Synology so I didn't really try
